### ISSUE TITLE
add classes if they don't exist

### ISSUE THREAD

**Issue by superr** [phhusson/sepolicy-inject#3]
Any chance of adding classes to sepolicy if they don't exist? I get many errors like this:
```
perm transition,siginh,rlimitinh,dyntransition does not exist in class process
Could not add rule
```
Thanks again for your support :)

**Comment by phhusson** [comment]
Your problem here is the permissions, not the class
and erm, sepolicy-inject doesn't support specifying multiple permissions on one command line yet. (though it's in the early todo list, I've got performance issues)

**Comment by superr** [comment]
so this line 
```
./sepolicy-inject -s init -t selinux_net -c process -p transition,siginh,rlimitinh,dyntransition -P sepolicy -o sepolicy2
```
needs to be
```
./sepolicy-inject -s init -t selinux_net -c process -p transition -P sepolicy -o sepolicy2
./sepolicy-inject -s init -t selinux_net -c process -p siginh -P sepolicy -o sepolicy2 
./sepolicy-inject -s init -t selinux_net -c process -p rlimitinh -P sepolicy -o sepolicy2 
./sepolicy-inject -s init -t selinux_net -c process -p dyntransition -P sepolicy -o sepolicy2 
```
Is this correct?

**Comment by phhusson** [comment]
Except for bad chaining sepolicy => sepolicy2, yup
You might want to use -P sepolicy without -o, it will override sepolicy.

**Comment by superr** [comment]
Yes, I wrote a script and started with the original that did not support overwriting. Another great addition :)
Thanks for the help :)

**Comment by phhusson** [comment]
No problem

**Comment by phhusson** [comment]
Ok I've made the support of ,-separated list of permissions, so
./sepolicy-inject -s init -t selinux_net -c process -p transition,siginh,rlimitinh,dyntransition -P sepolicy -o sepolicy2
should work now. That should give a HUGE boost in big scripts

**Comment by superr** [comment]
That is freaking awesome and way faster. Thank you so much :)

FYI, I am using your sepolicy-inject in my Android kitchen found here
http://forum.xda-developers.com/chef-central/android/kitchen-superrs-kitchen-t3202296
