### ISSUE TITLE
errors modifying Marshmallow sepolicy

### ISSUE THREAD

**Issue by superr** [phhusson/sepolicy-inject#4]
Hello again. For some reason, the new sepolicy-inject gives me errors when adding rules to Marshmallow sepolicy. I have attached the sepolicy here for your reference/testing. Rename .txt to .zip.

These are the errors I get:
```
error(s) encountered while parsing configuration
Could not load policy
libsepol.policydb_read: policydb version 30 does not match my version range 15-29
```
It works with the previous version without the multi perm support fyi. Thanks for your help :)

[sepolicy_Nexus9.txt](https://github.com/phhusson/sepolicy-inject/files/32220/sepolicy_Nexus9.txt)

**Comment by phhusson** [comment]
This is not my bug ;-)

You probably noticed there is a binary in this git repo. You exactly pointed to the reason why.
The version of libsepol used in Android is more recent than what is available in Debian (possibly they are using an unreleased libsepol). So you must build sepolicy-inject with Android's libsepol.

For the sake of simplicity, I put the statically-linked binary in this git repo.

**Comment by superr** [comment]
I completely understand. The problem is that not everyone uses 64-bit Linux (I know, get with the program). As a result I have the kitchen build the binaries so everyone can use it regardless of arch. I modified your makefile to detect 32/64 already for this purpose.

In the end, I guess I am asking how to get the missing Android libsepol to compile this. Thanks again :)

**Comment by phhusson** [comment]
Ok, I built a 32bits version of Android's libsepol by hand (cd AOSP/external/selinux/libsepol/src/; make CFLAGS=-m32)
And pushed both 32bits and 64bits version of the lib.

I'd appreciate a patch/PR which changes Makefile to refer to the proper lib.

**Comment by superr** [comment]
Thank you very much. I will submit a pull request when it is all sorted :)
